# Generated by Django 4.2.4 on 2024-04-18 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='product_name',
            new_name='productName',
        ),
    ]
