# Generated by Django 4.2.4 on 2024-04-06 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='description',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
