# Generated by Django 4.2.4 on 2024-04-06 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='name',
            new_name='projectName',
        ),
    ]
