# Generated by Django 4.2.4 on 2024-04-08 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_category_alter_product_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='product',
            name='modifier',
        ),
        migrations.RemoveField(
            model_name='product',
            name='project',
        ),
        migrations.AddField(
            model_name='product',
            name='creator_id',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='modifier_id',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='project_id',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
