# Generated by Django 4.2.4 on 2024-04-09 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_product_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='permission_level',
        ),
    ]
