# Generated by Django 4.2.4 on 2024-04-09 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_user_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='permission_level',
            field=models.IntegerField(default=0),
        ),
    ]
