# Generated by Django 4.2.4 on 2024-04-09 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_permission_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='permission_level',
            field=models.CharField(max_length=50),
        ),
    ]
